sudo: false
language: node_js
addons:
    apt:
        packages:
            - php5-common
            - php5-cli
            - php5-sqlite
            - php5-gd
            - php5-curl
before_install:
  - npm install gulp -g
node_js:
  - 'iojs-v1'
